name: PHPUnit + Build ZIP

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  main:
    name: Build, Test & Package
    strategy:
      matrix:
        php-versions: ['7.2', '7.3', '7.4']

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer, pecl, phpunit
          extensions: intl, json, mbstring, mysqlnd, xdebug, xml, sqlite3

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_ENV

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ env.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install --no-progress --no-suggest --no-interaction --prefer-dist --optimize-autoloader

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit --coverage-text

      - name: Prepare deploy folder
        run: |
          rm -rf deploy
          mkdir deploy
          # copy project files
          cp -r app bootstrap config database public resources routes vendor artisan deploy/
          # copy DB dummy
          if [ -f database/dummy.sql ]; then cp database/dummy.sql deploy/database.sql; fi
          # copy env example
          if [ -f .env.example ]; then cp .env.example deploy/.env; fi
          echo "Deploy folder contents:"
          ls -R deploy

      - name: Create ZIP package
        run: |
          cd deploy
          zip -r ../project-deploy.zip ./*
          cd ..
          echo "ZIP created at project-deploy.zip"

      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: project-deploy
          path: project-deploy.zip
